config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness:  { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    | The
    = link_to "https://railstutorial.jp/"
      |  Ruby on Rails Tutorial
    | by
    = link_to "http://www.michaelhartl.com/"
      |  Michael Hartl
  nav
    ul
      li = link_to "About", about_path
      li = link_to "Contact", contact_path
      li = link_to "News", 'http://news.railstutorial.org/'

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "sample app", root_path,  id: "logo"
    nav
    ul.nav.navbar-nav.navbar-right
      li = link_to "Home",   root_path
      li = link_to "Help",   help_path
      li = link_to "Login",   '#'

app/views/layouts/_shim.html.slim
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
/[endif]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  body
  = render 'layouts/header'
  .container
  = yield
  = render 'layouts/footer'

app/views/static_pages/about.html.slim
= provide(:title, "About")
h1 about

app/views/static_pages/contact.html.slim
= provide(:title, "Contact")
h1 StaticPages#Contact

app/views/static_pages/help.html.slim
= provide(:title, "Help")
h1 StaticPages#help
p Find me in app/views/static_pages/help.html.slim

app/views/static_pages/home.html.slim
.center.jumbotron
  h1 Welcome to the Sample App
  h2
    | This is the home page for the
    = link_to 'Ruby on Rails Tutorial', 'https://railstutorial.jp/'
    sample application.
  = link_to "Sign up now!", '#', class: "btn btn-lg btn-primary"
= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/'

app/views/users/new.html.slim
h1 Users#new
p Find me in app/views/users/new.html.slim